### ISSUE TITLE
1 Speaker 2 Dialects syllable stress not properly encoded

### ISSUE THREAD

**Issue by vannawillerton** [MontrealCorpusTools/ISCAN#201] opened 2019-05-23 15:09 UTC
When running tutorials 1 and 2 to test the One Speaker Two Dialects corpus in ISCAN, the syllable stress does not appear to get encoded properly. I can see this only when saving the CSV export file from my queries, the column for syllable stress is empty. 

I have not seen this problem in export files from other corpora, so it appears to be specific to this dataset.

The enrichments all ran completely fine, including the relevant 'stress from word pattern' using 'stresspattern'.

**Comment by msonderegger** [comment] 2019-05-24 15:02
I've assigned this to @MichaelGoodale , as he will already be figuring out stress-related issues with Unisyn.

No great rush, though.

**Comment by vannawillerton** [comment] 2019-05-27 14:21
@MichaelGoodale turns out this problem also applies to Glasgow Brains in Dialogue Corpus. Same exact issue as above.

**Comment by msonderegger** [comment] 2019-06-18 14:46
@vannawillerton is this issue resolved using the new lexical enrichment files (which James uploaded to SPADE), where stress is done right?

**Comment by msonderegger** [comment] 2019-06-27 15:55
Confirmed by Vanna this is still an issue, so @MichaelGoodale please investigate, consulting with Vanna as needed. Thanks!

**Comment by MichaelGoodale** [comment] 2019-07-04 17:57
Seems to be resolved, at least on my computer.

**Closed by MichaelGoodale** 2019-07-04 17:57 UTC
Labels: enrichment
